### PR TITLE
Add day details ,home page, component test

### PR DESCRIPTION
**Pull request by tamoorsaeed22**
### Implementations in this project
I create a SPA to show the weather of countries from Open-Meteo API. I follow this requirement
Interactions
Interactions

Home page

-  When the page loads, the web app shows the list of categories that could be filtered out by some parameter, for example by the category name.
- Along with the category name, you will display some numeric values per category that come from the API.
-  When the user clicks (or taps) on a category item, the application navigates to the details page.

Details page

-  In the details page, the web app retrieves data from the API to show detailed data in the category.
- When the user clicks on the "Back" button (<), the user navigates to the home page.

Testing requirements
- Create unit tests for pure functions in your Redux code.
- Create integration tests for your application using the React Testing Library.
- You may need to mock the access to the API so that your tests don't send actual requests.
-  You may need to mock the connection to the Redux Store.

### CODE REVIEW

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi @tamoorsaeed22, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have other linters checked except for the Netlify, I will encourage you to install all the needed linters like eslint and others as you've been doing.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by tamoorsaeed22** [comment]
@Olamarx yes mate it has been resolved linters are working and it was just because of some glitch.

**Comment by Olamarx** [comment]
> @Olamarx yes mate it has been resolved linters are working and it was just because of some glitch.

Good work, man.

**Comment by tamoorsaeed22** [comment]
@Olamarx thanks mate I tried my best

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi @tamoorsaeed22, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
- Linters passed ✔️
- All tests passed ✔️
- Readme file professional ✔️

## Required Changes ♻️
_Check the comments under the review._
- [x] You did a wonderful job and I would have approved it but there is an issue with the styling. You will notice that there is an overflow in the UI, I marked the section, kindly work on it so that it would be pixel-perfect.

image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tamoorsaeed22** [comment]
@Olamarx I got it and fix the overflow issue

**Review by omarsalem7 — APPROVED** [review]
Hi @tamoorsaeed22 😊, 
# STATUS: APPROVED! 🥇 💯 



Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
